.TH QUOTE 1 2024-02-23 3.0.0 ""
.SH NAME
\fBquote\fR \- Quote lines
.SH SYNOPSIS
.nf
\fBquote\fR
\fBquote\fR <quote>
\fBquote\fR <start-quote> <end-quote>
.fi
.SH DESCRIPTION
Quote lines, optionally using the specified quote character(s).
.SH OPTIONS
.TP
\fB\-h, \-\-help\fR
Print help\.
.TP
\fB\-v\, \-\-version\fR
Print the version\.
