.TH QUOTE 1 2024-02-14 1.1.0 ""
.SH NAME
\fBquote\fR \- Quote lines
.SH SYNOPSIS
\fBquote\fR ([\fB-q\fR \fI<quote>\fR] | [\fB-s\fR \fI<start>\fR] [\fB-e\fR \fI<end>\fR]) [\fI<file> \.\.\.\fR]
.SH DESCRIPTION
Quote lines, optionally using the specified quote character(s).
.SH OPTIONS
.TP
\fB\-q, \-\-quote\fR
The quote character\.
.TP
\fB\-s, \-\-start\fR
The staring quote character\.
.TP
\fB\-e, \-\-end\fR
The ending quote character\.
.TP
\fB\-h, \-\-help\fR
Print help\.
.TP
\fB\-v\, \-\-version\fR
Print the version\.
